### ISSUE TITLE
Error when editing appearance of exhibit

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/pomegranate#174]
```ruby
I, [2017-01-04T10:57:50.557969 #28305]  INFO -- : Completed 500 Internal Server Error in 637ms (ActiveRecord: 7.5ms)
F, [2017-01-04T10:57:50.560718 #28305] FATAL -- :
F, [2017-01-04T10:57:50.560889 #28305] FATAL -- : ActionView::Template::Error (undefined method `document_show_html_title' for #<#<Class:0x007f9f6923dee8>:0x007f9f56095018>):
F, [2017-01-04T10:57:50.561121 #28305] FATAL -- :     12:     <div>
F, [2017-01-04T10:57:50.561251 #28305] FATAL -- :     13:       <%= f.hidden_field(:document_global_id) %>
F, [2017-01-04T10:57:50.561373 #28305] FATAL -- :     14:       <%= f.hidden_field(:remote_image_url, data: jcrop_options) %>
F, [2017-01-04T10:57:50.561493 #28305] FATAL -- :     15:       <%= text_field_tag(:document_title, (presenter(f.object.document).document_show_html_title if f.object.document), class: "form-control", data: {input_select_target: "##{form_prefix}_source_exhibit", masthead_typeahead: true, target_panel: "##{form_prefix}-target-panel", :'id-field' => "##{form_prefix}_document_global_id", remote_url_field: "##{form_prefix}_remote_image_url" }) %>
F, [2017-01-04T10:57:50.561691 #28305] FATAL -- :     16:       <div id="<%= form_prefix %>-target-panel" style="display:none">
F, [2017-01-04T10:57:50.561809 #28305] FATAL -- :     17:         <div class="panel-heading">
F, [2017-01-04T10:57:50.561923 #28305] FATAL -- :     18:           <div data-item-title="true"></div>
F, [2017-01-04T10:57:50.562038 #28305] FATAL -- :
F, [2017-01-04T10:57:50.562183 #28305] FATAL -- : blacklight-spotlight (0.29.1) app/views/spotlight/featured_images/_form.html.erb:15:in `block in __opt_rails_app_shared_bundle_ruby_______gems_blacklight_spotlight________app_views_spotlight_featured_images__form_html_erb___3851923714473782469_70161044311880'
F, [2017-01-04T10:57:50.562307 #28305] FATAL -- : actionview (5.0.0.1) lib/action_view/helpers/capture_helper.rb:39:in `block in capture'
F, [2017-01-04T10:57:50.562425 #28305] FATAL -- : actionview (5.0.0.1) lib/action_view/helpers/capture_helper.rb:203:in `with_output_buffer'
F, [2017-01-04T10:57:50.562541 #28305] FATAL -- : actionview (5.0.0.1) lib/action_view/helpers/capture_helper.rb:39:in `capture'
F, [2017-01-04T10:57:50.562660 #28305] FATAL -- : actionview (5.0.0.1) lib/action_view/helpers/form_tag_helper.rb:588:in `field_set_tag'
F, [2017-01-04T10:57:50.562775 #28305] FATAL -- : blacklight-spotlight (0.29.1) app/views/spotlight/featured_images/_form.html.erb:9:in `__opt_rails_app_shared_bundle_ruby_______gems_blacklight_spotlight________app_views_spotlight_featured_images__form_html_erb___3851923714473782469_70161044311880'

```

Might be something to patch in spotlight.

**Comment by jpstroop** [comment]
Going to need this one fixed soonish so that Joyce can can start working with the application.
