### ISSUE TITLE
Error when adding user

### ISSUE THREAD

**Issue by escowles** [pulibrary/pomegranate#283]
When I try to add a user to a collection, I get the following error:

```
Completed 500 Internal Server Error in 36ms (ActiveRecord: 6.0ms)
  
NoMethodError (undefined method `password' for #<User:0x007fecd461c510>):
  
activemodel (5.0.0.1) lib/active_model/attribute_methods.rb:433:in `method_missing'
devise_invitable (1.7.1) lib/devise_invitable/model.rb:290:in `_invite'
devise_invitable (1.7.1) lib/devise_invitable/model.rb:310:in `invite!'
/opt/rails_app/shared/bundle/ruby/2.2.0/bundler/gems/spotlight-8ffeaf7cdf7f/app/models/spotlight/role.rb:33:in `user_must_exist'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:382:in `block in make_lambda'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:150:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:150:in `block (2 levels) in halting_and_conditional'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:547:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:547:in `block (2 levels) in default_terminator'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:546:in `catch'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:546:in `block in default_terminator'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:151:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:151:in `block in halting_and_conditional'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:454:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:454:in `block in call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:454:in `each'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:454:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_validate_callbacks'
activemodel (5.0.0.1) lib/active_model/validations.rb:408:in `run_validations!'
activemodel (5.0.0.1) lib/active_model/validations/callbacks.rb:113:in `block in run_validations!'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_validation_callbacks'
activemodel (5.0.0.1) lib/active_model/validations/callbacks.rb:113:in `run_validations!'
activemodel (5.0.0.1) lib/active_model/validations.rb:338:in `valid?'
activerecord (5.0.0.1) lib/active_record/validations.rb:65:in `valid?'
activerecord (5.0.0.1) lib/active_record/autosave_association.rb:332:in `association_valid?'
activerecord (5.0.0.1) lib/active_record/autosave_association.rb:320:in `block in validate_collection_association'
activerecord (5.0.0.1) lib/active_record/autosave_association.rb:320:in `each'
activerecord (5.0.0.1) lib/active_record/autosave_association.rb:320:in `each_with_index'
activerecord (5.0.0.1) lib/active_record/autosave_association.rb:320:in `validate_collection_association'
activerecord (5.0.0.1) lib/active_record/autosave_association.rb:219:in `block in define_autosave_validation_callbacks'
activerecord (5.0.0.1) lib/active_record/autosave_association.rb:158:in `instance_eval'
activerecord (5.0.0.1) lib/active_record/autosave_association.rb:158:in `block in define_non_cyclic_method'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:382:in `block in make_lambda'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:169:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:547:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:547:in `block (2 levels) in default_terminator'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:546:in `catch'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:546:in `block in default_terminator'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:170:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:170:in `block in halting'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:454:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:454:in `block in call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:454:in `each'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:454:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_validate_callbacks'
activemodel (5.0.0.1) lib/active_model/validations.rb:408:in `run_validations!'
activemodel (5.0.0.1) lib/active_model/validations/callbacks.rb:113:in `block in run_validations!'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_validation_callbacks'
activemodel (5.0.0.1) lib/active_model/validations/callbacks.rb:113:in `run_validations!'
activemodel (5.0.0.1) lib/active_model/validations.rb:338:in `valid?'
activerecord (5.0.0.1) lib/active_record/validations.rb:65:in `valid?'
activerecord (5.0.0.1) lib/active_record/validations.rb:82:in `perform_validations'
activerecord (5.0.0.1) lib/active_record/validations.rb:44:in `save'
activerecord (5.0.0.1) lib/active_record/attribute_methods/dirty.rb:22:in `save'
activerecord (5.0.0.1) lib/active_record/transactions.rb:319:in `block (2 levels) in save'
activerecord (5.0.0.1) lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
activerecord (5.0.0.1) lib/active_record/connection_adapters/abstract/database_statements.rb:230:in `transaction'
activerecord (5.0.0.1) lib/active_record/transactions.rb:211:in `transaction'
activerecord (5.0.0.1) lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
activerecord (5.0.0.1) lib/active_record/transactions.rb:319:in `block in save'
activerecord (5.0.0.1) lib/active_record/transactions.rb:334:in `rollback_active_record_state!'
activerecord (5.0.0.1) lib/active_record/transactions.rb:318:in `save'
activerecord (5.0.0.1) lib/active_record/suppressor.rb:41:in `save'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/active_record_5.rb:15:in `block in save'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/transaction.rb:858:in `with_database_metric_name'
newrelic_rpm (3.17.2.327) lib/new_relic/agent.rb:584:in `with_database_metric_name'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/active_record_5.rb:14:in `save'
activerecord (5.0.0.1) lib/active_record/persistence.rb:266:in `block in update'
activerecord (5.0.0.1) lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status'
activerecord (5.0.0.1) lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction'
activerecord (5.0.0.1) lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction'
activerecord (5.0.0.1) lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction'
activerecord (5.0.0.1) lib/active_record/transactions.rb:211:in `transaction'
activerecord (5.0.0.1) lib/active_record/transactions.rb:392:in `with_transaction_returning_status'
activerecord (5.0.0.1) lib/active_record/persistence.rb:264:in `update'
/opt/rails_app/shared/bundle/ruby/2.2.0/bundler/gems/spotlight-8ffeaf7cdf7f/app/controllers/spotlight/roles_controller.rb:22:in `update_all'
actionpack (5.0.0.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.0.0.1) lib/abstract_controller/base.rb:188:in `process_action'
actionpack (5.0.0.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.0.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.0.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.0.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.0.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.0.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.0.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.0.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (5.0.0.1) lib/abstract_controller/base.rb:126:in `process'
actionview (5.0.0.1) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.0.1) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.0.1) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
railties (5.0.0.1) lib/rails/engine.rb:522:in `call'
railties (5.0.0.1) lib/rails/railtie.rb:193:in `public_send'
railties (5.0.0.1) lib/rails/railtie.rb:193:in `method_missing'
actionpack (5.0.0.1) lib/action_dispatch/routing/mapper.rb:17:in `block in <class:Constraints>'
actionpack (5.0.0.1) lib/action_dispatch/routing/mapper.rb:46:in `call'
actionpack (5.0.0.1) lib/action_dispatch/routing/mapper.rb:46:in `serve'
actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `each'
actionpack (5.0.0.1) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.0.1) lib/action_dispatch/routing/route_set.rb:725:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
omniauth (1.3.1) lib/omniauth/strategy.rb:186:in `call!'
omniauth (1.3.1) lib/omniauth/strategy.rb:164:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (2.0.1) lib/rack/etag.rb:25:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (2.0.1) lib/rack/conditional_get.rb:38:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (2.0.1) lib/rack/head.rb:12:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (2.0.1) lib/rack/session/abstract/id.rb:222:in `context'
rack (2.0.1) lib/rack/session/abstract/id.rb:216:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.0.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.0.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
railties (5.0.0.1) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `block in tagged'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.0.1) lib/active_support/tagged_logging.rb:70:in `tagged'
railties (5.0.0.1) lib/rails/rack/logger.rb:24:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
request_store (1.3.2) lib/request_store/middleware.rb:9:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (2.0.1) lib/rack/method_override.rb:22:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (2.0.1) lib/rack/runtime.rb:22:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
activesupport (5.0.0.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
actionpack (5.0.0.1) lib/action_dispatch/middleware/static.rb:136:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
rack (2.0.1) lib/rack/sendfile.rb:111:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
honeybadger (2.7.2) lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
honeybadger (2.7.2) lib/honeybadger/config.rb:192:in `with_request'
honeybadger (2.7.2) lib/honeybadger/rack/error_notifier.rb:30:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
honeybadger (2.7.2) lib/honeybadger/rack/user_feedback.rb:28:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
honeybadger (2.7.2) lib/honeybadger/rack/user_informer.rb:18:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
railties (5.0.0.1) lib/rails/engine.rb:522:in `call'
newrelic_rpm (3.17.2.327) lib/new_relic/agent/instrumentation/middleware_tracing.rb:96:in `call'
/usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:97:in `process_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:160:in `accept_and_process_next_request'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:113:in `main_loop'
/usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:416:in `block (3 levels) in start_threads'
/usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'
```

**Comment by tpendragon** [comment]
Duplicate of https://github.com/pulibrary/pomegranate/issues/256 ?

**Comment by escowles** [comment]
Yep, looks like a dupe.

**Comment by joycebcat** [comment]
Eric told me that he has logged in.  The other ticket assumes that the person has never logged in.

**Comment by tpendragon** [comment]
Something must have gone wrong - the database has nobody recorded with the username "ericwhite"
