### ISSUE TITLE
Errors importing collections in development with webrick

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/pomegranate#408]
```
[2018-07-24 15:50:01] ERROR Errno::ECONNRESET: Connection reset by peer @ io_fillbuf - fd:45 
    /Users/headleya/.rubies/ruby-2.4.3/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `eof?'
    /Users/headleya/.rubies/ruby-2.4.3/lib/ruby/2.4.0/webrick/httpserver.rb:82:in `run'
    /Users/headleya/.rubies/ruby-2.4.3/lib/ruby/2.4.0/webrick/server.rb:308:in `block in start_thread'
```
This is resolved by switching to puma. PR forthcoming.

**Comment by hackmastera** [comment]
Except `rails s` seems to be thrashing or going insane for some reason on puma.
