### ISSUE TITLE
reindexing problem with a new set of EAL Supplementary Materials

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/pomegranate#534]
Here's a view of it from the console:
```
irb(main):014:0> r = IIIFResource.find(4162)                                                                                                                                                                            [11/313]
=> #<IIIFResource id: 4162, exhibit_id: 15, type: "IIIFResource", url: "https://figgy.princeton.edu/concern/scanned_resour...", data: {"noid"=>"44558h041"}, indexed_at: nil, created_at: "2017-12-14 00:21:47", updated_at: "20
17-12-14 00:21:47", metadata: nil, index_status: nil, upload_id: nil>
irb(main):015:0> Spotlight::ReindexJob.perform_now([r])
Performing Spotlight::ReindexJob from Sidekiq(default) with arguments: [#<GlobalID:0x00000000091bea00 @uri=#<URI::GID gid://pomegranate/IIIFResource/4162>>]
Failed to update Solr for the following documents: e643f8f835574cfe78b42082611237d4
Performed Spotlight::ReindexJob from Sidekiq(default) in 4826.16ms
IIIFResource::IndexingError: Failed to update Solr for the following documents: e643f8f835574cfe78b42082611237d4
        from /opt/dpul/releases/20190222170800/app/models/iiif_resource.rb:68:in `rescue in write_to_index'
        from /opt/dpul/releases/20190222170800/app/models/iiif_resource.rb:59:in `write_to_index'
        from /opt/dpul/shared/bundle/ruby/2.4.0/bundler/gems/spotlight-0ff14576f874/app/models/spotlight/resource.rb:53:in `block (3 levels) in reindex'
        from /opt/dpul/shared/bundle/ruby/2.4.0/bundler/gems/spotlight-0ff14576f874/app/models/spotlight/resource.rb:52:in `each_slice'
        from /opt/dpul/shared/bundle/ruby/2.4.0/bundler/gems/spotlight-0ff14576f874/app/models/spotlight/resource.rb:52:in `block (2 levels) in reindex'
        from /opt/dpul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:126:in `call'
        from /opt/dpul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
        from /opt/dpul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:455:in `call'
        from /opt/dpul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
        from /opt/dpul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:750:in `_run_index_callbacks'
        from /opt/dpul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:90:in `run_callbacks'
        from /opt/dpul/shared/bundle/ruby/2.4.0/bundler/gems/spotlight-0ff14576f874/app/models/spotlight/resource.rb:51:in `block in reindex'
        from /opt/dpul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7/lib/active_support/benchmarkable.rb:41:in `block in benchmark'
        from /opt/dpul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
        from /usr/lib/ruby/2.4.0/benchmark.rb:308:in `realtime'
        from /opt/dpul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7/lib/active_support/core_ext/benchmark.rb:12:in `ms'
... 41 levels...
        from /opt/dpul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:285:in `block in halting'
        from /opt/dpul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:447:in `block in around'
        from /opt/dpul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:455:in `call'
        from /opt/dpul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
        from /opt/dpul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:750:in `_run_perform_callbacks'
        from /opt/dpul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:90:in `run_callbacks'
        from /opt/dpul/shared/bundle/ruby/2.4.0/gems/activejob-5.0.7/lib/active_job/execution.rb:33:in `perform_now'
        from /opt/dpul/shared/bundle/ruby/2.4.0/gems/activejob-5.0.7/lib/active_job/execution.rb:16:in `perform_now'
        from (irb):15
        from /opt/dpul/shared/bundle/ruby/2.4.0/gems/railties-5.0.7/lib/rails/commands/console.rb:65:in `start'
        from /opt/dpul/shared/bundle/ruby/2.4.0/gems/railties-5.0.7/lib/rails/commands/console_helper.rb:9:in `start'
        from /opt/dpul/shared/bundle/ruby/2.4.0/gems/railties-5.0.7/lib/rails/commands/commands_tasks.rb:78:in `console'
        from /opt/dpul/shared/bundle/ruby/2.4.0/gems/railties-5.0.7/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        from /opt/dpul/shared/bundle/ruby/2.4.0/gems/railties-5.0.7/lib/rails/commands.rb:18:in `<top (required)>'
        from bin/rails:9:in `require'
        from bin/rails:9:in `<main>'
```

**Comment by hackmastera** [comment]
here's the error in the sneakers log:
```
2019-02-28T15:07:24Z p-31071 t-jhzj0 ERROR: [Exception error="undefined method `has_key?' for #<Array:0x00007f7104bc53f0>" error_class=NoMethodError worker_class=FiggyEventHandler backtrace=/opt/dpul/shared/bundle/ruby/2.4.0/gems/iiif-presentation-0.1.0/lib/iiif/service.rb:202:in `from_ordered_hash',/opt/dpul/shared/bundle/ruby/2.4.0/gems/iiif-presentation-0.1.0/lib/iiif/service.rb:210:in `block in from_ordered_hash',/opt/dpul/shared/bundle/ruby/2.4.0/gems/iiif-presentation-0.1.0/lib/iiif/service.rb:207:in `each',/opt/dpul/shared/bundle/ruby/2.4.0/gems/iiif-presentation-0.1.0/lib/iiif/service.rb:207:in `from_ordered_hash',/opt/dpul/shared/bundle/ruby/2.4.0/gems/iiif-presentation-0.1.0/lib/iiif/service.rb:50:in `parse',/opt/dpul/shared/bundle/ruby/2.4.0/bundler/gems/spotlight-0ff14576f874/app/models/spotlight/resources/iiif_service.rb:33:in `object',/opt/dpul/shared/bundle/ruby/2.4.0/bundler/gems/spotlight-0ff14576f874/app/models/spotlight/resources/iiif_service.rb:88:in `block in build_collection_manifest',/opt/dpul/shared/bundle/ruby/2.4.0/bundler/gems/spotlight-0ff14576f874/app/models/spotlight/resources/iiif_service.rb:87:in `each',/opt/dpul/shared/bundle/ruby/2.4.0/bundler/gems/spotlight-0ff14576f874/app/models/spotlight/resources/iiif_service.rb:87:in `build_collection_manifest',/opt/dpul/shared/bundle/ruby/2.4.0/bundler/gems/spotlight-0ff14576f874/app/models/spotlight/resources/iiif_service.rb:22:in `each',/opt/dpul/shared/bundle/ruby/2.4.0/bundler/gems/spotlight-0ff14576f874/app/models/spotlight/resources/iiif_service.rb:22:in `to_a',/opt/dpul/shared/bundle/ruby/2.4.0/bundler/gems/spotlight-0ff14576f874/app/models/spotlight/resources/iiif_service.rb:22:in `manifests',/opt/dpul/shared/bundle/ruby/2.4.0/bundler/gems/spotlight-0ff14576f874/app/models/spotlight/resources/iiif_service.rb:53:in `recursive_manifests',/opt/dpul/releases/20190222170800/app/models/iiif_resource.rb:17:in `each',/opt/dpul/releases/20190222170800/app/models/iiif_resource.rb:17:in `to_a',/opt/dpul/releases/20190222170800/app/models/iiif_resource.rb:17:in `validate_iiif_manifest_collections!',/opt/dpul/releases/20190222170800/app/models/iiif_resource.rb:10:in `iiif_manifests',/opt/dpul/releases/20190222170800/app/models/iiif_resource.rb:48:in `set_noid',/opt/dpul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:382:in `block in make_lambda',/opt/dpul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:169:in `block (2 levels) in halting',/opt/dpul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:770:in `block (2 levels) in deprecated_false_terminator',/opt/dpul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:769:in `catch',/opt/dpul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:769:in `block in deprecated_false_terminator',/opt/dpul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:170:in `block in halting',/opt/dpul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:454:in `block in call',/opt/dpul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:454:in `each',/opt/dpul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:454:in `call',/opt/dpul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:101:in `__run_callbacks__',/opt/dpul/shared/bundle/ruby/2.4.0/gems/activesupport-5.0.7/lib/active_support/callbacks.rb:750:in `_run_save_callbacks',/opt/dpul/shared/bundle/ruby/2.4.0/gems/activerecord-5.0.7/lib/active_record/callbacks.rb:298:in `create_or_update',/opt/dpul/shared/bundle/ruby/2.4.0/gems/activerecord-5.0.7/lib/active_record/persistence.rb:129:in `save',/opt/dpul/shared/bundle/ruby/2.4.0/gems/activerecord-5.0.7/lib/active_record/validations.rb:44:in `save',/opt/dpul/shared/bundle/ruby/2.4.0/gems/activerecord-5.0.7/lib/active_record/attribute_methods/dirty.rb:22:in `save',/opt/dpul/shared/bundle/ruby/2.4.0/gems/activerecord-5.0.7/lib/active_record/transactions.rb:319:in `block (2 levels) in save',/opt/dpul/shared/bundle/ruby/2.4.0/gems/activerecord-5.0.7/lib/active_record/transactions.rb:395:in `block in with_transaction_returning_status',/opt/dpul/shared/bundle/ruby/2.4.0/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `block in transaction',/opt/dpul/shared/bundle/ruby/2.4.0/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/transaction.rb:189:in `within_new_transaction',/opt/dpul/shared/bundle/ruby/2.4.0/gems/activerecord-5.0.7/lib/active_record/connection_adapters/abstract/database_statements.rb:232:in `transaction',/opt/dpul/shared/bundle/ruby/2.4.0/gems/activerecord-5.0.7/lib/active_record/transactions.rb:211:in `transaction',/opt/dpul/shared/bundle/ruby/2.4.0/gems/activerecord-5.0.7/lib/active_record/transactions.rb:392:in `with_transaction_returning_status',/opt/dpul/shared/bundle/ruby/2.4.0/gems/activerecord-5.0.7/lib/active_record/transactions.rb:319:in `block in save',/opt/dpul/shared/bundle/ruby/2.4.0/gems/activerecord-5.0.7/lib/active_record/transactions.rb:334:in `rollback_active_record_state!',/opt/dpul/shared/bundle/ruby/2.4.0/gems/activerecord-5.0.7/lib/active_record/transactions.rb:318:in `save',/opt/dpul/shared/bundle/ruby/2.4.0/gems/activerecord-5.0.7/lib/active_record/suppressor.rb:41:in `save',/opt/dpul/shared/bundle/ruby/2.4.0/bundler/gems/spotlight-0ff14576f874/app/models/spotlight/resource.rb:28:in `save_and_index',/opt/dpul/releases/20190222170800/app/services/figgy_event_processor/update_processor.rb:41:in `block in create_new_resources',/opt/dpul/shared/bundle/ruby/2.4.0/gems/activerecord-5.0.7/lib/active_record/relation/delegation.rb:38:in `each',/opt/dpul/shared/bundle/ruby/2.4.0/gems/activerecord-5.0.7/lib/active_record/relation/delegation.rb:38:in `each',/opt/dpul/releases/20190222170800/app/services/figgy_event_processor/update_processor.rb:40:in `create_new_resources',/opt/dpul/releases/20190222170800/app/services/figgy_event_processor/update_processor.rb:6:in `process']
2019-02-28T15:07:24Z p-31071 t-jhzj0 INFO: Maxretry handler [queue=pomegranate_production] msg=retrying, count=1, headers=

```

**Comment by hackmastera** [comment]
This looks like the same error as #527, which is an object in a different collection.

**Comment by hackmastera** [comment]
Found a bit of data that is causing the bug

```
From: /Users/headleya/.gem/ruby/2.4.3/gems/iiif-presentation-0.1.0/lib/iiif/service.rb @ line 205 IIIF::Service.from_ordered_hash:

    200:       # Create a new object (new_object)
    201:       type = nil
    202:       if hsh.is_a? Array
    203:         binding.pry
    204:       end
 => 205:       if hsh.has_key?('@type')
    206:         type = IIIF::Service.get_descendant_class_by_jld_type(hsh['@type'])
    207:       end
    208:       new_object = type.nil? ? default_klass.new : type.new
    209:
    210:       hsh.keys.each do |key|

[1] pry(IIIF::Service)> hsh
=> [{"@context"=>"http://iiif.io/api/search/0/context.json",
  "@id"=>"https://figgy.princeton.edu/catalog/c7f0bb99-3721-4171-8a84-0256941e8298/iiif_search",
  "profile"=>"http://iiif.io/api/search/0/search",
  "label"=>"Search within this item"}]
[2] pry(IIIF::Service)>

```

To replicate do something like this:
```
exhibit = Spotlight::Exhibit.find_by(slug: "some_slug")
bad_manifest = "https://figgy.princeton.edu/concern/scanned_resources/dba865ab-9a37-4436-a52f-564a2b6bd8f0/manifest"
bad = IIIFResource.find_or_initialize_by(url: bad_manifest, exhibit_id: exhibit.id)
bad.save_and_index_now
```
