### ISSUE TITLE
Resolve figgy-staging error queue

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/pomegranate#777]
Need to figure out how to read the payload.

This issue should be closed when the queue is empty, and issues have been created to resolve errors that seem likely to recur.

One example error looks like this:

```
{"error":"undefined method `has_key?' for #\u003cArray:0x00007f46182525c8\u003e","num_attempts":6,"failed_at":"2020-01-21T17:38:45-05:00","payload":"eyJpZCI6IjM0MGNiMjJhLWJmMWYtNDRiNS05Y2VhLWYxYzIyMzY3ZThkNCIs\nImV2ZW50IjoiVVBEQVRFRCIsIm1hbmlmZXN0X3VybCI6Imh0dHBzOi8vZmln\nZ3ktc3RhZ2luZy5wcmluY2V0b24uZWR1L2NvbmNlcm4vc2Nhbm5lZF9yZXNv\ndXJjZXMvMzQwY2IyMmEtYmYxZi00NGI1LTljZWEtZjFjMjIzNjdlOGQ0L21h\nbmlmZXN0IiwiY29sbGVjdGlvbl9zbHVncyI6WyJ0ZXN0Y29sIl19\n","properties":"W1siY29udGVudF90eXBlIiwiYXBwbGljYXRpb24vb2N0ZXQtc3RyZWFtIl0s\nWyJoZWFkZXJzIix7IngtZGVhdGgiOlt7ImNvdW50Ijo1LCJleGNoYW5nZSI6\nInBvbWVncmFuYXRlX3N0YWdpbmctcmV0cnkiLCJxdWV1ZSI6InBvbWVncmFu\nYXRlX3N0YWdpbmctcmV0cnkiLCJyZWFzb24iOiJleHBpcmVkIiwicm91dGlu\nZy1rZXlzIjpbIiJdLCJ0aW1lIjoiMjAyMC0wMS0yMVQxNzoyOTo0NS4wMDAt\nMDU6MDAifSx7ImNvdW50Ijo1LCJleGNoYW5nZSI6ImZpZ2d5X2V2ZW50cyIs\nInF1ZXVlIjoicG9tZWdyYW5hdGVfc3RhZ2luZyIsInJlYXNvbiI6InJlamVj\ndGVkIiwicm91dGluZy1rZXlzIjpbIiJdLCJ0aW1lIjoiMjAyMC0wMS0yMVQx\nNzoyODozOC4wMDAtMDU6MDAifV0sIngtZmlyc3QtZGVhdGgtZXhjaGFuZ2Ui\nOiJmaWdneV9ldmVudHMiLCJ4LWZpcnN0LWRlYXRoLXF1ZXVlIjoicG9tZWdy\nYW5hdGVfc3RhZ2luZyIsIngtZmlyc3QtZGVhdGgtcmVhc29uIjoicmVqZWN0\nZWQifV0sWyJkZWxpdmVyeV9tb2RlIiwyXSxbInByaW9yaXR5IiwwXV0=\n","error_class":"NoMethodError","error_message":"undefined method `has_key?' for #\u003cArray:0x00007f46182525c8\u003e","backtrace":"/opt/dpul/shared/bundle/ruby/2.4.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:202:in `from_ordered_hash',
/opt/dpul/shared/bundle/ruby/2.4.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:210:in `block in from_ordered_hash',
/opt/dpul/shared/bundle/ruby/2.4.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:207:in `each',
/opt/dpul/shared/bundle/ruby/2.4.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:207:in `from_ordered_hash',
/opt/dpul/shared/bundle/ruby/2.4.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:214:in `block in from_ordered_hash',
/opt/dpul/shared/bundle/ruby/2.4.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:207:in `each',
/opt/dpul/shared/bundle/ruby/2.4.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:207:in `from_ordered_hash',
/opt/dpul/shared/bundle/ruby/2.4.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:221:in `block (2 levels) in from_ordered_hash',
/opt/dpul/shared/bundle/ruby/2.4.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:217:in `each',
/opt/dpul/shared/bundle/ruby/2.4.0/gems/iiif-presentation-0.2.0/lib/iiif/service.rb:217:in `block in from_ordered_hash'"}

```

**Comment by tpendragon** [comment]
The payload is base64 encoded.

**Comment by hackmastera** [comment]
Great, thanks. Added some notes on that to https://github.com/pulibrary/pomegranate/wiki/RabbitMQ---Sneakers

**Comment by hackmastera** [comment]
Moved these back to the pomegranate_staging queue and they ran through fine.
