### ISSUE TITLE
Missing blacklight.yml config file -- error from rabbitmq error queue

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/pomegranate#786]
there are 2 of these. one header and both payloads below.

```
{"error":"You are missing a configuration file: /opt/dpul/releases/20200504141824/config/blacklight.yml. Have you run \"rails generate blacklight:install\"?","num_attempts":6,"failed_at":"2020-05-04T14:58:54+00:00","properties":{"content_type":"application/octet-stream","headers":{"x-death":[{"count":5,"exchange":"pomegranate_production-retry","queue":"pomegranate_production-retry","reason":"expired","routing-keys":[""],"time":"2020-05-04T14:54:53.000+00:00"},{"count":5,"exchange":"figgy_events","queue":"pomegranate_production","reason":"rejected","routing-keys":[""],"time":"2020-05-04T14:53:53.000+00:00"}],"x-first-death-exchange":"figgy_events","x-first-death-queue":"pomegranate_production","x-first-death-reason":"rejected"},"delivery_mode":2,"priority":0},"error_class":"RuntimeError","error_message":"You are missing a configuration file: /opt/dpul/releases/20200504141824/config/blacklight.yml. Have you run \"rails generate blacklight:install\"?","backtrace":["/opt/dpul/shared/bundle/ruby/2.6.0/gems/blacklight-6.20.0/lib/blacklight.rb:77:in `blacklight_yml'","/opt/dpul/shared/bundle/ruby/2.6.0/gems/blacklight-6.20.0/lib/blacklight.rb:62:in `connection_config'","/opt/dpul/shared/bundle/ruby/2.6.0/gems/blacklight-6.20.0/lib/blacklight/configuration.rb:211:in `connection_config'","/opt/dpul/shared/bundle/ruby/2.6.0/gems/blacklight-6.20.0/lib/blacklight/abstract_repository.rb:50:in `connection_config'","/opt/dpul/shared/bundle/ruby/2.6.0/gems/blacklight-6.20.0/lib/blacklight/solr/repository.rb:88:in `build_connection'","/opt/dpul/shared/bundle/ruby/2.6.0/gems/blacklight-6.20.0/lib/blacklight/abstract_repository.rb:17:in `connection'","/opt/dpul/shared/bundle/ruby/2.6.0/gems/blacklight-6.20.0/lib/blacklight/solr/repository.rb:61:in `block in send_and_receive'","/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/benchmarkable.rb:43:in `block in benchmark'","/opt/dpul/shared/bundle/ruby/2.6.0/gems/activesupport-5.2.3/lib/active_support/core_ext/benchmark.rb:14:in `block in ms'","/usr/lib/ruby/2.6.0/benchmark.rb:308:in `realtime'"]}

payload: {"id":"2190535d-fa3a-4b80-8022-da93c7db8946","event":"UPDATED","manifest_url":"https://figgy.princeton.edu/concern/scanned_resources/2190535d-fa3a-4b80-8022-da93c7db8946/manifest","collection_slugs":["lapidus_pamphlets","lapidus"]}
```

Another one's payload:
```
{"id":"2c225f85-288f-4b41-8e3c-eaaf5d6123c6","event":"UPDATED","manifest_url":"https://figgy.princeton.edu/concern/ephemera_folders/2c225f85-288f-4b41-8e3c-eaaf5d6123c6/manifest","collection_slugs":["soviet_posters","slavic"]}
```

**Comment by hackmastera** [comment]
Re-queued all messages from the error queue after resolving #784 and #785. No longer getting this error; closing.
