### ISSUE TITLE
"cannot load translations" from rabbitmq error queue

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/pomegranate#787]
There are 5 of these, all for the same collection though.

```
{"error":"can not load translations from /opt/dpul/releases/20200504141824/config/locales/blacklight.en.yml: #\u003cErrno::ENOENT: No such file or directory @ rb_sysopen - /opt/dpul/releases/20200504141824/config/locales/blacklight.en.yml\u003e","num_attempts":6,"failed_at":"2020-05-04T15:04:56+00:00","properties":{"content_type":"application/octet-stream","headers":{"x-death":[{"count":5,"exchange":"pomegranate_production-retry","queue":"pomegranate_production-retry","reason":"expired","routing-keys":[""],"time":"2020-05-04T15:00:53.000+00:00"},{"count":5,"exchange":"figgy_events","queue":"pomegranate_production","reason":"rejected","routing-keys":[""],"time":"2020-05-04T14:59:53.000+00:00"}],"x-first-death-exchange":"figgy_events","x-first-death-queue":"pomegranate_production","x-first-death-reason":"rejected"},"delivery_mode":2,"priority":0},"error_class":"I18n::InvalidLocaleData","error_message":"can not load translations from /opt/dpul/releases/20200504141824/config/locales/blacklight.en.yml: #\u003cErrno::ENOENT: No such file or directory @ rb_sysopen - /opt/dpul/releases/20200504141824/config/locales/blacklight.en.yml\u003e","backtrace":["/opt/dpul/shared/bundle/ruby/2.6.0/gems/i18n-1.8.2/lib/i18n/backend/base.rb:244:in `rescue in load_yml'","/opt/dpul/shared/bundle/ruby/2.6.0/gems/i18n-1.8.2/lib/i18n/backend/base.rb:240:in `load_yml'","/opt/dpul/shared/bundle/ruby/2.6.0/gems/i18n-1.8.2/lib/i18n/backend/base.rb:225:in `load_file'","/opt/dpul/shared/bundle/ruby/2.6.0/gems/i18n-1.8.2/lib/i18n/backend/base.rb:18:in `block in load_translations'","/opt/dpul/shared/bundle/ruby/2.6.0/gems/i18n-1.8.2/lib/i18n/backend/base.rb:18:in `each'","/opt/dpul/shared/bundle/ruby/2.6.0/gems/i18n-1.8.2/lib/i18n/backend/base.rb:18:in `load_translations'","/opt/dpul/shared/bundle/ruby/2.6.0/gems/i18n-1.8.2/lib/i18n/backend/simple.rb:80:in `init_translations'","/opt/dpul/shared/bundle/ruby/2.6.0/gems/i18n-1.8.2/lib/i18n/backend/simple.rb:90:in `lookup'","/opt/dpul/shared/bundle/ruby/2.6.0/gems/i18n-1.8.2/lib/i18n/backend/memoize.rb:41:in `lookup'","/opt/dpul/shared/bundle/ruby/2.6.0/gems/i18n-1.8.2/lib/i18n/backend/base.rb:32:in `translate'"]}

payload: {"id":"2c225f85-288f-4b41-8e3c-eaaf5d6123c6","event":"UPDATED","manifest_url":"https://figgy.princeton.edu/concern/ephemera_folders/2c225f85-288f-4b41-8e3c-eaaf5d6123c6/manifest","collection_slugs":["soviet_posters","slavic"]}
```

**Comment by hackmastera** [comment]
Re-queued all messages from the error queue after resolving #784 and #785. No longer getting this error; closing.
